# Generated by Django 4.2.6 on 2023-10-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('origem', models.CharField(default='BR', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.IntegerField(choices=[(1, 'Mouse'), (2, 'Teclado'), (3, 'Mousepad'), (4, 'Fone'), (5, 'Monitor')])),
                ('preco', models.FloatField(default=0, max_length=20)),
                ('slug', models.SlugField(default='')),
                ('descricao', models.TextField(default='')),
                ('estoque', models.IntegerField(default=0)),
                ('data_pub', models.DateTimeField(verbose_name='Data de publicacao')),
                ('marca', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.marca')),
            ],
        ),
    ]
