# Generated by Django 4.2.6 on 2023-10-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_pedidoproduto_conjuntoproduto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConjuntoProduto',
            new_name='Compra',
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
