# Generated by Django 4.2.6 on 2023-10-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_conjuntoproduto_compra_alter_compra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmado'), (2, 'Enviado'), (3, 'Entrgue')], default=1),
        ),
    ]
