# Generated by Django 4.2.6 on 2023-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pedido_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='Venda',
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aguardando envio'), (2, 'Enviado'), (3, 'Entregue')], default=1),
        ),
    ]
