# Generated by Django 4.2.6 on 2023-10-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_compra_venda_alter_venda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
